;(function(){var h,k=this;function l(a){return void 0!==a}
function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ba(a){var b=aa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function m(a){return"string"==typeof a}var ca=Date.now||function(){return+new Date};function p(a,b){a=a.split(".");var c=k;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};function r(a,b){return-1!=a.indexOf(b)};var da=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};function ea(a,b){a:{for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:m(a)?a.charAt(b):a[b]}function fa(a){return Array.prototype.concat.apply(Array.prototype,arguments)}
function ha(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var u;a:{var ia=k.navigator;if(ia){var ja=ia.userAgent;if(ja){u=ja;break a}}u=""}function v(a){return r(u,a)};function ka(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function la(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function ma(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function na(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function oa(a,b){for(var c=ba(b),d=c?b:arguments,c=c?0:1;c<d.length&&(a=a[d[c]],l(a));c++);return a}
function pa(a){var b=arguments.length;if(1==b&&"array"==aa(arguments[0]))return pa.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};function qa(){return(v("Chrome")||v("CriOS"))&&!v("Edge")};function ra(){v("iPod")}function sa(){return v("iPhone")&&!v("iPod")&&!v("iPad")};v("Opera");v("Trident")||v("MSIE");v("Edge");!v("Gecko")||r(u.toLowerCase(),"webkit")&&!v("Edge")||v("Trident")||v("MSIE")||v("Edge");r(u.toLowerCase(),"webkit")&&!v("Edge")&&v("Mobile");v("Macintosh");v("Windows");v("Linux")||v("CrOS");var ta=k.navigator||null;ta&&r(ta.appVersion||"","X11");v("Android");sa();v("iPad");ra();function w(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};v("Firefox");sa()||ra();v("iPad");!v("Android")||qa()||v("Firefox")||v("Opera")||v("Silk");qa();!v("Safari")||qa()||v("Coast")||v("Opera")||v("Edge")||v("Silk")||v("Android")||sa()||v("iPad")||ra();function ua(a){if(a.s&&"function"==typeof a.s)return a.s();if(m(a))return a.split("");if(ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ma(a)}
function va(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(ba(a)||m(a))da(a,b,c);else{var d;if(a.B&&"function"==typeof a.B)d=a.B();else if(a.s&&"function"==typeof a.s)d=void 0;else if(ba(a)||m(a)){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else d=na(a);for(var e=ua(a),g=e.length,f=0;f<g;f++)b.call(c,e[f],d&&d[f],a)}};function wa(a,b){this.v={};this.j=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)}h=wa.prototype;h.O=function(){return this.c};h.s=function(){xa(this);for(var a=[],b=0;b<this.j.length;b++)a.push(this.v[this.j[b]]);return a};h.B=function(){xa(this);return this.j.concat()};h.F=function(a){return y(this.v,a)};
h.equals=function(a,b){if(this===a)return!0;if(this.c!=a.O())return!1;b=b||ya;xa(this);for(var c,d=0;c=this.j[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function ya(a,b){return a===b}h.clear=function(){this.v={};this.c=this.j.length=0};h.remove=function(a){return y(this.v,a)?(delete this.v[a],this.c--,this.j.length>2*this.c&&xa(this),!0):!1};
function xa(a){if(a.c!=a.j.length){for(var b=0,c=0;b<a.j.length;){var d=a.j[b];y(a.v,d)&&(a.j[c++]=d);b++}a.j.length=c}if(a.c!=a.j.length){for(var e={},c=b=0;b<a.j.length;)d=a.j[b],y(e,d)||(a.j[c++]=d,e[d]=1),b++;a.j.length=c}}h.get=function(a,b){return y(this.v,a)?this.v[a]:b};h.set=function(a,b){y(this.v,a)||(this.c++,this.j.push(a));this.v[a]=b};h.addAll=function(a){var b;a instanceof wa?(b=a.B(),a=a.s()):(b=na(a),a=ma(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};
h.forEach=function(a,b){for(var c=this.B(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};h.clone=function(){return new wa(this)};function y(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var za=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function Aa(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e,g=null;0<=d?(e=a[c].substring(0,d),g=a[c].substring(d+1)):e=a[c];b(e,g?decodeURIComponent(g.replace(/\+/g," ")):"")}}};function A(a,b){this.m=this.H=this.D="";this.I=null;this.G=this.l="";this.u=this.U=!1;var c;a instanceof A?(this.u=l(b)?b:a.u,Ba(this,a.D),c=a.H,B(this),this.H=c,c=a.m,B(this),this.m=c,Ca(this,a.I),c=a.l,B(this),this.l=c,Da(this,a.A.clone()),a=a.G,B(this),this.G=a):a&&(c=String(a).match(za))?(this.u=!!b,Ba(this,c[1]||"",!0),a=c[2]||"",B(this),this.H=C(a),a=c[3]||"",B(this),this.m=C(a,!0),Ca(this,c[4]),a=c[5]||"",B(this),this.l=C(a,!0),Da(this,c[6]||"",!0),a=c[7]||"",B(this),this.G=C(a)):(this.u=!!b,
this.A=new D(null,0,this.u))}h=A.prototype;h.toString=function(){var a=[],b=this.D;b&&a.push(E(b,Ea,!0),":");var c=this.m;if(c||"file"==b)a.push("//"),(b=this.H)&&a.push(E(b,Ea,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.I,null!=c&&a.push(":",String(c));if(c=this.l)this.m&&"/"!=c.charAt(0)&&a.push("/"),a.push(E(c,"/"==c.charAt(0)?Fa:Ga,!0));(c=this.A.toString())&&a.push("?",c);(c=this.G)&&a.push("#",E(c,Ha));return a.join("")};
h.resolve=function(a){var b=this.clone(),c=!!a.D;c?Ba(b,a.D):c=!!a.H;if(c){var d=a.H;B(b);b.H=d}else c=!!a.m;c?(d=a.m,B(b),b.m=d):c=null!=a.I;d=a.l;if(c)Ca(b,a.I);else if(c=!!a.l){if("/"!=d.charAt(0))if(this.m&&!this.l)d="/"+d;else{var e=b.l.lastIndexOf("/");-1!=e&&(d=b.l.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(r(e,"./")||r(e,"/.")){for(var d=0==e.lastIndexOf("/",0),e=e.split("/"),g=[],f=0;f<e.length;){var n=e[f++];"."==n?d&&f==e.length&&g.push(""):".."==n?((1<g.length||1==g.length&&
""!=g[0])&&g.pop(),d&&f==e.length&&g.push("")):(g.push(n),d=!0)}d=g.join("/")}else d=e}c?(B(b),b.l=d):c=""!==a.A.toString();c?Da(b,C(a.A.toString())):c=!!a.G;c&&(a=a.G,B(b),b.G=a);return b};h.clone=function(){return new A(this)};function Ba(a,b,c){B(a);a.D=c?C(b,!0):b;a.D&&(a.D=a.D.replace(/:$/,""))}function Ca(a,b){B(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.I=b}else a.I=null}
function Da(a,b,c){B(a);b instanceof D?(a.A=b,a.A.P(a.u)):(c||(b=E(b,Ia)),a.A=new D(b,0,a.u));return a}h.setQuery=function(a,b){return Da(this,a,b)};h.getQuery=function(){return this.A.toString()};function B(a){if(a.U)throw Error("Tried to modify a read-only Uri");}h.P=function(a){this.u=a;this.A&&this.A.P(a);return this};function C(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}
function E(a,b,c){return m(a)?(a=encodeURI(a).replace(b,Ja),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Ja(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Ea=/[#\/\?@]/g,Ga=/[\#\?:]/g,Fa=/[\#\?]/g,Ia=/[\#\?@]/g,Ha=/#/g;function D(a,b,c){this.c=this.g=null;this.o=a||null;this.u=!!c}function F(a){a.g||(a.g=new wa,a.c=0,a.o&&Aa(a.o,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}h=D.prototype;h.O=function(){F(this);return this.c};
h.add=function(a,b){F(this);this.o=null;a=G(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.c+=1;return this};h.remove=function(a){F(this);a=G(this,a);return this.g.F(a)?(this.o=null,this.c-=this.g.get(a).length,this.g.remove(a)):!1};h.clear=function(){this.g=this.o=null;this.c=0};h.F=function(a){F(this);a=G(this,a);return this.g.F(a)};h.B=function(){F(this);for(var a=this.g.s(),b=this.g.B(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
h.s=function(a){F(this);var b=[];if(m(a))this.F(a)&&(b=fa(b,this.g.get(G(this,a))));else{a=this.g.s();for(var c=0;c<a.length;c++)b=fa(b,a[c])}return b};h.set=function(a,b){F(this);this.o=null;a=G(this,a);this.F(a)&&(this.c-=this.g.get(a).length);this.g.set(a,[b]);this.c+=1;return this};h.get=function(a,b){a=a?this.s(a):[];return 0<a.length?String(a[0]):b};
h.toString=function(){if(this.o)return this.o;if(!this.g)return"";for(var a=[],b=this.g.B(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.s(d),g=0;g<d.length;g++){var f=e;""!==d[g]&&(f+="="+encodeURIComponent(String(d[g])));a.push(f)}return this.o=a.join("&")};h.clone=function(){var a=new D;a.o=this.o;this.g&&(a.g=this.g.clone(),a.c=this.c);return a};function G(a,b){b=String(b);a.u&&(b=b.toLowerCase());return b}
h.P=function(a){a&&!this.u&&(F(this),this.o=null,this.g.forEach(function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<a.length&&(this.o=null,this.g.set(G(this,d),ha(a)),this.c+=a.length))},this));this.u=a};h.extend=function(a){for(var b=0;b<arguments.length;b++)va(arguments[b],function(a,b){this.add(b,a)},this)};function Ka(a){this.K=a||{cookie:""}}var La=/\s*;\s*/;h=Ka.prototype;h.isEnabled=function(){return navigator.cookieEnabled};h.set=function(a,b,c,d,e,g){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');l(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";g=g?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(ca()+1E3*c)).toUTCString();this.K.cookie=a+"="+b+e+d+c+g};
h.get=function(a,b){for(var c=a+"=",d=(this.K.cookie||"").split(La),e=0,g;g=d[e];e++){if(0==g.lastIndexOf(c,0))return g.substr(c.length);if(g==a)return""}return b};h.remove=function(a,b,c){var d=this.F(a);this.set(a,"",0,b,c);return d};h.B=function(){return Ma(this).keys};h.s=function(){return Ma(this).values};h.O=function(){return this.K.cookie?(this.K.cookie||"").split(La).length:0};h.F=function(a){return l(this.get(a))};h.clear=function(){for(var a=Ma(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
function Ma(a){a=(a.K.cookie||"").split(La);for(var b=[],c=[],d,e,g=0;e=a[g];g++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}}var H=new Ka("undefined"==typeof document?null:document);H.W=3950;var Na=null;function Oa(){this.C=-1};function I(){this.C=64;this.i=Array(4);this.T=Array(this.C);this.M=this.J=0;this.reset()}(function(){function a(){}a.prototype=Oa.prototype;I.fa=Oa.prototype;I.prototype=new a;I.prototype.constructor=I;I.Z=function(a,c,d){for(var e=Array(arguments.length-2),g=2;g<arguments.length;g++)e[g-2]=arguments[g];return Oa.prototype[c].apply(a,e)}})();I.prototype.reset=function(){this.i[0]=1732584193;this.i[1]=4023233417;this.i[2]=2562383102;this.i[3]=271733878;this.M=this.J=0};
function Pa(a,b,c){c||(c=0);var d=Array(16);if(m(b))for(var e=0;16>e;++e)d[e]=b.charCodeAt(c++)|b.charCodeAt(c++)<<8|b.charCodeAt(c++)<<16|b.charCodeAt(c++)<<24;else for(e=0;16>e;++e)d[e]=b[c++]|b[c++]<<8|b[c++]<<16|b[c++]<<24;b=a.i[0];c=a.i[1];var e=a.i[2],g=a.i[3],f;f=b+(g^c&(e^g))+d[0]+3614090360&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[1]+3905402710&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&(b^c))+d[2]+606105819&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+
d[3]+3250441966&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(g^c&(e^g))+d[4]+4118548399&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[5]+1200080426&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&(b^c))+d[6]+2821735955&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+d[7]+4249261313&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(g^c&(e^g))+d[8]+1770035416&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[9]+2336552879&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&
(b^c))+d[10]+4294925233&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+d[11]+2304563134&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(g^c&(e^g))+d[12]+1804603682&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[13]+4254626195&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&(b^c))+d[14]+2792965006&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+d[15]+1236535329&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(e^g&(c^e))+d[1]+4129170786&4294967295;b=c+(f<<5&4294967295|f>>>
27);f=g+(c^e&(b^c))+d[6]+3225465664&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[11]+643717713&4294967295;e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[0]+3921069994&4294967295;c=e+(f<<20&4294967295|f>>>12);f=b+(e^g&(c^e))+d[5]+3593408605&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[10]+38016083&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[15]+3634488961&4294967295;e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[4]+3889429448&4294967295;c=e+(f<<20&4294967295|
f>>>12);f=b+(e^g&(c^e))+d[9]+568446438&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[14]+3275163606&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[3]+4107603335&4294967295;e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[8]+1163531501&4294967295;c=e+(f<<20&4294967295|f>>>12);f=b+(e^g&(c^e))+d[13]+2850285829&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[2]+4243563512&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[7]+1735328473&4294967295;e=g+(f<<14&4294967295|
f>>>18);f=c+(g^b&(e^g))+d[12]+2368359562&4294967295;c=e+(f<<20&4294967295|f>>>12);f=b+(c^e^g)+d[5]+4294588738&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[8]+2272392833&4294967295;g=b+(f<<11&4294967295|f>>>21);f=e+(g^b^c)+d[11]+1839030562&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[14]+4259657740&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(c^e^g)+d[1]+2763975236&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[4]+1272893353&4294967295;g=b+(f<<11&4294967295|f>>>21);f=e+(g^
b^c)+d[7]+4139469664&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[10]+3200236656&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(c^e^g)+d[13]+681279174&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[0]+3936430074&4294967295;g=b+(f<<11&4294967295|f>>>21);f=e+(g^b^c)+d[3]+3572445317&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[6]+76029189&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(c^e^g)+d[9]+3654602809&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[12]+3873151461&4294967295;
g=b+(f<<11&4294967295|f>>>21);f=e+(g^b^c)+d[15]+530742520&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[2]+3299628645&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(e^(c|~g))+d[0]+4096336452&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[7]+1126891415&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[14]+2878612391&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[5]+4237533241&4294967295;c=e+(f<<21&4294967295|f>>>11);f=b+(e^(c|~g))+d[12]+1700485571&4294967295;b=c+
(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[3]+2399980690&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[10]+4293915773&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[1]+2240044497&4294967295;c=e+(f<<21&4294967295|f>>>11);f=b+(e^(c|~g))+d[8]+1873313359&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[15]+4264355552&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[6]+2734768916&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[13]+1309151649&4294967295;
c=e+(f<<21&4294967295|f>>>11);f=b+(e^(c|~g))+d[4]+4149444226&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[11]+3174756917&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[2]+718787259&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[9]+3951481745&4294967295;a.i[0]=a.i[0]+b&4294967295;a.i[1]=a.i[1]+(e+(f<<21&4294967295|f>>>11))&4294967295;a.i[2]=a.i[2]+e&4294967295;a.i[3]=a.i[3]+g&4294967295}
I.prototype.update=function(a,b){l(b)||(b=a.length);for(var c=b-this.C,d=this.T,e=this.J,g=0;g<b;){if(0==e)for(;g<=c;)Pa(this,a,g),g+=this.C;if(m(a))for(;g<b;){if(d[e++]=a.charCodeAt(g++),e==this.C){Pa(this,d);e=0;break}}else for(;g<b;)if(d[e++]=a[g++],e==this.C){Pa(this,d);e=0;break}}this.J=e;this.M+=b};
I.prototype.digest=function(){var a=Array((56>this.J?this.C:2*this.C)-this.J);a[0]=128;for(var b=1;b<a.length-8;++b)a[b]=0;for(var c=8*this.M,b=a.length-8;b<a.length;++b)a[b]=c&255,c/=256;this.update(a);a=Array(16);for(b=c=0;4>b;++b)for(var d=0;32>d;d+=8)a[c++]=this.i[b]>>>d&255;return a};function J(a,b){this.f=a|0;this.a=b|0}var Qa={},K={};function L(a){return-128<=a&&128>a?w(Qa,a,function(a){return new J(a|0,0>a?-1:0)}):new J(a|0,0>a?-1:0)}function M(a){return isNaN(a)?N():a<=-Ra?O():a+1>=Ra?Sa():0>a?P(M(-a)):new J(a%Q|0,a/Q|0)}var Q=4294967296,Ra=Q*Q/2;function N(){return w(K,Ta,function(){return L(0)})}function R(){return w(K,Ua,function(){return L(1)})}function Va(){return w(K,Wa,function(){return L(-1)})}function Sa(){return w(K,Xa,function(){return new J(-1,2147483647)})}
function O(){return w(K,Ya,function(){return new J(0,-2147483648)})}function Za(){return w(K,$a,function(){return L(16777216)})}h=J.prototype;
h.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(S(this))return"0";if(0>this.a){if(this.equals(O())){var b=M(a),c=T(this,b),b=c.multiply(b).subtract(this);return c.toString(a)+b.f.toString(a)}return"-"+P(this).toString(a)}for(var c=M(Math.pow(a,6)),b=this,d="";;){var e=T(b,c),g=(b.subtract(e.multiply(c)).f>>>0).toString(a),b=e;if(S(b))return g+d;for(;6>g.length;)g="0"+g;d=""+g+d}};function ab(a){return 0<=a.f?a.f:Q+a.f}function S(a){return 0==a.a&&0==a.f}
h.equals=function(a){return this.a==a.a&&this.f==a.f};h.compare=function(a){if(this.equals(a))return 0;var b=0>this.a,c=0>a.a;return b&&!c?-1:!b&&c?1:0>this.subtract(a).a?-1:1};function P(a){return a.equals(O())?O():a.not().add(R())}h.add=function(a){var b=this.a>>>16,c=this.a&65535,d=this.f>>>16,e=a.a>>>16,g=a.a&65535,f=a.f>>>16;a=0+((this.f&65535)+(a.f&65535));f=0+(a>>>16)+(d+f);d=0+(f>>>16);d+=c+g;b=0+(d>>>16)+(b+e)&65535;return new J((f&65535)<<16|a&65535,b<<16|d&65535)};h.subtract=function(a){return this.add(P(a))};
h.multiply=function(a){if(S(this)||S(a))return N();if(this.equals(O()))return 1==(a.f&1)?O():N();if(a.equals(O()))return 1==(this.f&1)?O():N();if(0>this.a)return 0>a.a?P(this).multiply(P(a)):P(P(this).multiply(a));if(0>a.a)return P(this.multiply(P(a)));if(0>this.compare(Za())&&0>a.compare(Za()))return M((this.a*Q+ab(this))*(a.a*Q+ab(a)));var b=this.a>>>16,c=this.a&65535,d=this.f>>>16,e=this.f&65535,g=a.a>>>16,f=a.a&65535,n=a.f>>>16;a=a.f&65535;var t,q,x,z;z=0+e*a;x=0+(z>>>16)+d*a;q=0+(x>>>16);x=(x&
65535)+e*n;q+=x>>>16;q+=c*a;t=0+(q>>>16);q=(q&65535)+d*n;t+=q>>>16;q=(q&65535)+e*f;t=t+(q>>>16)+(b*a+c*n+d*f+e*g)&65535;return new J((x&65535)<<16|z&65535,t<<16|q&65535)};
function T(a,b){if(S(b))throw Error("division by zero");if(S(a))return N();if(a.equals(O())){if(b.equals(R())||b.equals(Va()))return O();if(b.equals(O()))return R();var c;c=1;if(0==c)c=a;else{var d=a.a;c=32>c?new J(a.f>>>c|d<<32-c,d>>c):new J(d>>c-32,0<=d?0:-1)}c=T(c,b).shiftLeft(1);if(c.equals(N()))return 0>b.a?R():Va();a=a.subtract(b.multiply(c));return c.add(T(a,b))}if(b.equals(O()))return N();if(0>a.a)return 0>b.a?T(P(a),P(b)):P(T(P(a),b));if(0>b.a)return P(T(a,P(b)));for(d=N();0<=a.compare(b);){c=
Math.max(1,Math.floor((a.a*Q+ab(a))/(b.a*Q+ab(b))));for(var e=Math.ceil(Math.log(c)/Math.LN2),e=48>=e?1:Math.pow(2,e-48),g=M(c),f=g.multiply(b);0>f.a||0<f.compare(a);)c-=e,g=M(c),f=g.multiply(b);S(g)&&(g=R());d=d.add(g);a=a.subtract(f)}return d}function bb(a,b){return a.subtract(T(a,b).multiply(b))}h.not=function(){return new J(~this.f,~this.a)};h.and=function(a){return new J(this.f&a.f,this.a&a.a)};
h.shiftLeft=function(a){a&=63;if(0==a)return this;var b=this.f;return 32>a?new J(b<<a,this.a<<a|b>>>32-a):new J(0,b<<a-32)};var Xa=1,Ya=2,Ta=3,Ua=4,Wa=5,$a=6;k.V={"goog.array.ASSUME_NATIVE_FUNCTIONS":!0,"goog.DEBUG":!1,"goog.json.USE_NATIVE_JSON":!0,"goog.defineClass.SEAL_CLASS_INSTANCES":!1};var cb,db,eb;cb=k.lucidConfigure&&0==k.lucidConfigure.appid;eb=(db=k.lucidConfigure&&1==k.lucidConfigure.appid)?"press":"chart";function fb(){var a=/[.]?([a-zA-Z]+.com)/.exec(k.location&&k.location.hostname);return a?a[1]:"lucid"+eb+".com"};var U=function(){var a=k.screen,b="";if("screen"in k&&a.width)var c=a.width,d=a.height,b=b+(""+(c||"")+" x "+(d||""));var a=navigator.appVersion,e=navigator.userAgent,g="Other",f=""+parseFloat(navigator.appVersion),n=parseInt(navigator.appVersion,10),t;-1!=(n=e.indexOf("Opera"))&&(g="Opera",f=e.substring(n+6),-1!=(n=e.indexOf("Version"))&&(f=e.substring(n+8)));-1!=(n=e.indexOf("OPR"))?(g="Opera",f=e.substring(n+4)):-1!=(n=e.indexOf("Edge"))?(g="Edge",f=e.substring(n+5)):-1!=(n=e.indexOf("MSIE"))?
(g="IE",f=e.substring(n+5)):-1!=(n=e.indexOf("Chrome"))?(g="Chrome",f=e.substring(n+7)):-1!=(n=e.indexOf("Safari"))?(g="Safari",f=e.substring(n+7),-1!=(n=e.indexOf("Version"))&&(f=e.substring(n+8))):-1!=(n=e.indexOf("Firefox"))?(g="Firefox",f=e.substring(n+8)):-1!=e.indexOf("Trident/")&&(g="IE",f=e.substring(e.indexOf("rv:")+3));-1!=(t=f.indexOf(";"))&&(f=f.substring(0,t));-1!=(t=f.indexOf(" "))&&(f=f.substring(0,t));-1!=(t=f.indexOf(")"))&&(f=f.substring(0,t));n=parseInt(""+f,10);isNaN(n)&&(f=""+
parseFloat(navigator.appVersion),n=parseInt(navigator.appVersion,10));t=/Mobile|mini|Fennec|Android|iP(ad|od|hone)/.test(a);var q=navigator.cookieEnabled?!0:!1;"undefined"==typeof navigator.cookieEnabled&&!q&&"document"in k&&(document.cookie="testcookie",q=-1!=document.cookie.indexOf("testcookie")?!0:!1);var x="-";[{b:"Windows 10",r:/(Windows 10.0|Windows NT 10.0)/},{b:"Windows 8.1",r:/(Windows 8.1|Windows NT 6.3)/},{b:"Windows 8",r:/(Windows 8|Windows NT 6.2)/},{b:"Windows 7",r:/(Windows 7|Windows NT 6.1)/},
{b:"Windows Vista",r:/Windows NT 6.0/},{b:"Windows Server 2003",r:/Windows NT 5.2/},{b:"Windows XP",r:/(Windows NT 5.1|Windows XP)/},{b:"Windows 2000",r:/(Windows NT 5.0|Windows 2000)/},{b:"Windows ME",r:/(Win 9x 4.90|Windows ME)/},{b:"Windows 98",r:/(Windows 98|Win98)/},{b:"Windows 95",r:/(Windows 95|Win95|Windows_95)/},{b:"Windows NT 4.0",r:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{b:"Windows CE",r:/Windows CE/},{b:"Windows 3.11",r:/Win16/},{b:"Android",r:/Android/},{b:"Open BSD",r:/OpenBSD/},
{b:"Sun OS",r:/SunOS/},{b:"Linux",r:/(Linux|X11)/},{b:"iOS",r:/(iPhone|iPad|iPod)/},{b:"Mac OS X",r:/Mac OS X/},{b:"Mac OS",r:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/},{b:"QNX",r:/QNX/},{b:"UNIX",r:/UNIX/},{b:"BeOS",r:/BeOS/},{b:"OS/2",r:/OS\/2/},{b:"Search Bot",r:/(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver)/}].every(function(a){return a.r.test(e)?(x=a.b,!1):!0});var z="-";/Windows/.test(x)&&(z=/Windows (.*)/.exec(x)[1],x="Windows");switch(x){case "Mac OS X":z=/Mac OS X (10[\.\_\d]+)/.exec(e)[1];
break;case "Android":z=/Android ([\.\_\d]+)/.exec(e)[1];break;case "iOS":z=/OS (\d+)_(\d+)_?(\d+)?/.exec(a),z=z[1]+"."+z[2]+"."+(z[3]|0)}return{ea:b,screen:c&&d?{width:c,height:d}:null,browser:g,aa:f,N:n,ba:t,L:x,ca:z,cookies:q}}(),W=navigator.userAgent.toLowerCase(),X="IE"==U.browser,gb=X&&9==U.N,hb=X&&10==U.N,ib=X&&9<=U.N,jb=-1!=W.toLowerCase().indexOf("iphone"),kb=-1!=W.toLowerCase().indexOf("ipod");W.toLowerCase().indexOf("ipad");var lb=-1!=W.toLowerCase().indexOf("android");jb||kb||lb&&W.indexOf("mobile");
var mb="Edge"==U.browser,nb="Safari"==U.browser,ob="Chrome"==U.browser,pb="Firefox"==U.browser,qb=-1!=U.L.toLowerCase().indexOf("win")||-1!=U.L.toLowerCase().indexOf("16bit"),rb=-1!=U.L.toLowerCase().indexOf("mac"),sb=-1!=U.L.toLowerCase().indexOf("linux");p("lucid.useragent.is_mac",rb);p("lucid.useragent.is_linux",sb);p("lucid.useragent.is_win",qb);p("lucid.useragent.is_ie",X);p("lucid.useragent.is_ie9",gb);p("lucid.useragent.is_ie10",hb);p("lucid.useragent.is_edge",mb);
p("lucid.useragent.is_firefox",pb);p("lucid.useragent.is_safari",nb);p("lucid.useragent.is_chrome",ob);p("lucid.useragent.is_chrome_app",!1);p("lucid.useragent.redirectOldBrowsers",function(a){return X&&!ib?(k.location.href=a||"/pages/old_browser",!0):!1});p("lucid.useragent.all",U);function Y(a){return oa(k,"lucidConfigure",a)}Y("cdn_domain");Y("cashy_domain");Y("assets_base_url");Y("documentServiceHost");Y("imageServiceHost");Y("userServiceHost");Y("uimg_s3_domain");Y("uimg_s3_bucket");Y("editor_version_url");Y("uimg_cloudfront_domain");Y("fonts_preload_list");Y("fonts_cloudfront_public_list");Y("fonts_s3_url");Y("fonts_cloudfront_enabled");Y("buildVersion");Y("thumb_domain");Y("public_thumb_domain");Y("pdfProxyHost");Y("i18n_override");Y("pdf_polling_timeout");Y("default_color_profiles_url");
Y("featureFlags");Y("defaultChartTemplate");Y("visio_import_file_limit");Y("pressTutorialLesson1TemplateId");Y("portal-id");cb?Y("enterpriseSalesForm_chart"):Y("enterpriseSalesForm_press");Y("contactSalesForm_"+eb);Y("confluenceContactSalesForm");Y("domainLockdownForm");Y("enterpriseScimForm");Y("showvisio");Y("showgraffle");Y("showgliffy");Y("showsvg");Y("showindesign");Y("showdoclist");Y("showsequencemarkup");Y("newPDFData");p("lucid.togglePDFData",function(){});Y("abTestsEnabled");Y("on_premise");
Y("drupal_root");Y("spellingServiceHost");var tb=Y("analyticsServiceHost");Y("new_crop_controls_enabled");pa(Y("known_image_sizes")||[]);Y("eventServerHost");Y("product");Y("activityServiceHost");Y("conversionServiceHost");Y("commentOnboardingPayingOnly");Y("showOutlierDialog");Y("salesPhoneNumber");Y("gapi_key");Y("imageSearchCX");Y("salesEmail");Y("awsPlacementRetryLimit");Y("awsImportHubspotFormId");Y("NewEditorAbTests");Y("licenseTrialBlacklist");Y("private_thumb_domain");Y("private_thumb_cache_buster");
Y("private_thumb_enabled");Y("oneDriveClientId");Y("defaultFamily");function ub(a){if(k.lucidConfigure&&k.lucidConfigure.abTest)if((a=k.lucidConfigure.abTest[a])&&a.options){var b=a.startDate,c=a.endDate;a={name:a.name,options:a.options,ha:a.team,da:a.partitioningType,description:a.description,S:b?new Date(b):null,R:c?new Date(c):null}}else a=null;else a=null;return a}
function vb(a,b){var c=L(0);ma(b).forEach(function(a){if(0>a)throw"Option weights must be >= 0";c=c.add(L(a))});if(S(c))throw"Option weights must add up to a positive number";a=function(a){var b=new I;b.reset();b.update(a);a=b.digest();for(var b=L(0),c=0;8>c;c++)b=b.shiftLeft(8),b=b.add(L(a[c]));return b}("featureFlag|"+a);0>a.a&&(a=P(a));a=bb(a,c);for(var d="",e=na(b).sort(),g=0;g<e.length&&!(d=e[g],a=a.subtract(L(b[d])),0>a.a);g++);return d};function wb(a){if(k.innerHeight&&!H.get("visit_source")){var b;if(H.get("set_visit_source"))b=H.get("set_visit_source");else{b=new A(k.document.URL);var c=new A(k.document.referrer),d={},e;e=(k.location&&k.location.href.toString()||"").split("#");var g;g=1<e.length&&-1==e[0].indexOf("?")?e[1].substring(e[1].indexOf("?")+1||e[1].length).split("&"):e[0].substring(e[0].indexOf("?")+1||e[0].length).split("&");for(var f=0;f<g.length;f++)e=g[f].split("="),d[e[0].toString().toLowerCase()]=e[1]||"";a:{d=
[d.utm_source,null];e=d.length;for(g=0;g<e;g++)if(d[g]||0===d[g]||""===d[g]||!1===d[g]){d=d[g];break a}d=null}b=xb(d,c,b)}b=yb(b);a({"Better Visit Source Mk 3":b});H.set("visit_source",b,1800)}}p("lucid.kissMetrics.Source.recordVisitSource",wb);
function xb(a,b,c){var d;"string"===typeof a&&""!==a?(d="Campaign","google"===a?(b=zb(b),d=d+"-"+b):d+="-Other"):(d=b.m,d=r(d,"google.")?zb(b):r(d,"lucidchart.")?db?"Lucidchart":"Internal":r(d,"lucidpress.")?db?"Internal":"Lucidpress":b&&"Direct"!=b.l?"Other":"Direct");b=d+"-";c=r(c.l,"users")?"users":r(c.l,"pages")?"Landing":r(c.l,"documents")?"users":r(c.m,"www.lucidchart.com")||r(c.m,"www.lucidpress.com")?"HomePage":"other";return b+c}p("lucid.kissMetrics.Source.determineVisitSource",xb);
function zb(a){var b="Google";a=a.m;var c;if(c=r(a,"www.google"))c=a.length-10,c=!(0<=c&&a.indexOf("google.com",c)==c);return c?b+"-Foreign":b+"-Domestic"}
function yb(a){a=a.toLowerCase();if(0==a.lastIndexOf("campaign-",0))return Ab(a);if(0==a.lastIndexOf("google-",0))return Bb(a);switch(a){case "google docs add-on":return Cb;case "shareddocument":return Db;case "google apps":return Eb;case "google drive":return Fb;case "foreign":return Gb;case "blank-other":return Hb;case "direct-homepage":return Ib;case "chrome app store":return Jb;case "internal-users":return Kb;case "ios":return Lb;case "internal-landing":return Kb;case "google sheets add-on":return Mb;
case "interal-homepage":return Kb;case "other-homepage":return Nb;case "direct-users":return Ib;case "chromepackagedapp":return Ob;case "visioviewer":return Pb;case "direct-landing":return Ib;case "team invitation":return Z;case '"team invitation"':return Z;case "lucidchart":return Hb;case "confluence":return Qb;case "direct-other":return Ib;case "ipad":return Lb;case "chrome+app+store":return Jb;case "added by team admin":return Z;case "ondemand-confluence":return Qb;case "google+docs+add-on":return Cb;
case "added by team admin by csv upload":return Z;case "lucidchart-invitations":return Z;case '"google apps"':return Eb;case "chrome webstore":return Jb;case "shared document":return Db;case '"shared document"':return Db;default:return Rb}}function Ab(a){switch(a.toLowerCase()){case "campaign-google-domestic-landing":return Sb;case "campaign-google-foreign-landing":return Tb;case "campaign-google-foreign-homepage":return Ub;default:return Vb}}
function Bb(a){switch(a.toLowerCase()){case "google-foreign-landing":return Wb;case "google-domestic-homepage":return Xb;case "google-domestic-landing":return Yb;case "google-foreign-homepage":return Zb;case "google-domestic-users":return $b;case "google-foreign-users":return ac;default:return Rb}}
var Ub="Campaign-Google-Foreign-Homepage",Sb="Campaign-Google-Domestic-Landing",Tb="Campaign-Google-Foreign-Landing",Vb="Campaign-Other",Qb="Confluence",Jb="Chrome App Store",Ob="Chrome Packaged App",Ib="Direct",Gb="Foreign",Eb="Google Apps",Cb="Google Docs Addon",Fb="Google Drive",Xb="Google-Domestic-Homepage",Yb="Google-Domestic-Landing",$b="Google-Domestic-Users",Zb="Google-Foreign-Homepage",Wb="Google-Foreign-Landing",ac="Google-Foreign-Users",Mb="Google Sheets Addon",Kb="Internal",Lb="iOS",Nb=
"Other-HomePage",Rb="Other Source",Db="Shared Document",Z="Team Invitation",Pb="Visio Viewer",Hb="Web-Unknown";function bc(a){k._loq=k._loq||[];k._loq.push(["tag",a])}H.get("visit_source")&&bc("source-"+H.get("visit_source"));if(H.get("lo-tags")){var cc=decodeURIComponent(H.get("lo-tags")),dc=JSON.parse(cc);ka(dc,function(a,b){bc(b+"-"+a)});H.remove("lo-tags","/")};function ec(a){var b;return function(){if(!b){var c=new Date;if(!1===(k.lucidConfigure&&k.lucidConfigure.abTestsEnabled))b=null;else{var d=ub(a);if(d){var e;e=d.options||ub(a).options;var g=H.get("abTest_"+a.replace(/[\s=;]/g,"_"));e=g&&l(e[g])?g:(g=H.get("abTestAny"))&&l(e[g])?g:"";b=e?e:d.S&&c<d.S||d.R&&c>d.R?null:vb(a,d.options)}else b=null}}return"T-B"===b}}var fc=H.get("useKMProxy")&&"false"===H.get("useKMProxy")?!1:!0,gc=ec("ProxyKMRequests"),hc=ec("BatchKMProxyRequests");
function ic(){for(var a=new ArrayBuffer(20),a=new Uint8Array(a),b=0;20>b;b++)a[b]=Math.floor(256*Math.random());b=encodeURIComponent;if(!Na){Na={};for(var c=0;65>c;c++)Na[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)}for(var c=Na,d=[],e=0;e<a.length;e+=3){var g=a[e],f=e+1<a.length,n=f?a[e+1]:0,t=e+2<a.length,q=t?a[e+2]:0,x=g>>2,g=(g&3)<<4|n>>4,n=(n&15)<<2|q>>6,q=q&63;t||(q=64,f||(n=64));d.push(c[x],c[g],c[n],c[q])}return b(d.join(""))}
function jc(){var a=Array.isArray(k._kmq)?k._kmq:[];return(a=ea(a,function(a){return"identify"===a[0]}))?a[1]:void 0}
function kc(a){var b=a[0];if(b&&(a[1]||"clearIdentity"===b)){var c="clearIdentity"===b?"":a[1].toString(),d=("record"===b?a[2]:a[1])||null,e=0;"set"===b?e=2:"record"===b&&(e=3);a="function"==aa(a[e])?a[e]:void 0;"set"===b?lc(d,a):"record"===b?mc(c,d,a):"clearIdentity"===b||"identify"===b&&""===c?gc()&&fc?(H.get("km_ni")&&H.remove("km_ai","/"),H.remove("km_ni","/")):k._kmq.push(["clearIdentity"]):"identify"===b&&(gc()&&fc?(H.get("km_ni")&&H.set("km_ai",c,157788E3,"/",fb()),H.set("km_ni",c,157788E3,
"/",fb())):k._kmq.push(["identify",c]))}}function lc(a,b){gc()&&fc?(nc(void 0,a),b&&b()):k._kmq.push(["set",a,b])}p("lucid.kissMetrics.set",lc);function mc(a,b,c){gc()&&fc?(nc(a,b),c&&c()):k._kmq.push(["record",a,b,c])}function nc(a,b){b=b?la(b,function(a){return null!=a&&a.toString?a.toString():a}):b;a={event:a,properties:b};hc()?oc(a):pc(a)}
var oc=function(){function a(){0<b.length&&(pc(b),b=[]);c=void 0}var b=[],c,d;return function(e){b.push(e);d||(d=k.addEventListener("beforeunload",a));c||(c=setTimeout(a,1E3))}}();function pc(a){$.ajax({type:"POST",url:tb+"/kmProxy",contentType:"application/json",data:JSON.stringify(a),crossDomain:!0,xhrFields:{withCredentials:!0}})}
(function(){k._kmq||(k._kmq=[]);if(k._kmProxy&&Array.isArray(k._kmProxy)){var a=k._kmProxy.slice();k._kmProxy={push:kc};a.forEach(kc)}else k._kmProxy||(k._kmProxy={push:kc});k._kmProxyChecked||(k._kmProxyChecked=!0,k._kmq.push(["set",{adblocked:"false"},function(){H.set("useKMProxy","false",-1,"/")}]));a=H.get("km_ai");H.remove("km_ai","/");H.get("km_ai")||(a=a||jc()||ic(),H.set("km_ai",a,157788E3,"/",fb()));wb(function(a){lc(a);ka(a,function(a){bc("source-"+a)})})})();
p("lucid.kissMetrics.recordEvent",mc);})();
//# sourceMappingURL=/js/closure/source-maps/kmproxy.js.map